# 众筹服务配置文件
# 单链架构，支持多合约部署

server:
  port: "18888" # 服务器端口
  mode: "debug" # 运行模式: debug, release

database:
  host: "localhost" # 数据库主机地址
  port: 5432 # 数据库端口
  user: "postgres" # 数据库用户名
  password: "123456" # 数据库密码
  dbname: "crowdfunding" # 数据库名称
  sslmode: "disable" # SSL模式

# 单链配置
chain:
  chain_type: "ethereum"
  chain_id: 11155111
  rpc_url: "https://sepolia.infura.io/v3/77c2a505d62545429460e39cf6a094a6"
  private_key: "0x5baa4ed37e003885ecafcb8fe07d2a0bac4740b8d414655055a335ed899cf87b"

  # 该链上的合约配置
  contracts:
    counter:
      address: "0xc90698955C1cBD5d411F75c4adae0ba2D1Db6ef5"
      abi_path: "config/abi/Counter.json"
      enabled: true
      block_num: 9186975

task:
  # 任务执行间隔(秒)
  interval: 60

log:
  # 日志级别: debug, info, warn, error, fatal
  level: "debug"

  # 输出目标: stdout, stderr, file
  output: "stdout"

  # 日志文件路径（当output为file时使用）
  file: "logs/app.log"
