server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "crowdfunding"
  sslmode: "disable"

ethereum:
  rpc_url: "https://mainnet.infura.io/v3/YOUR_PROJECT_ID"
  private_key: "YOUR_PRIVATE_KEY"
  contract_address: "0x..."
  start_block: 0
  confirmations: 12

scheduler:
  interval: 60
